# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2957955880f24e631e4a12b8b7c0ab040359ae96d3b308c16fc4dac69f54758930999ad5bf5e362787b43a9ffdd8098b9fe000029fa297665f705ab45236282

test:
  secret_key_base: 2fca32d4036a1d10090d44060420ffb5e0f1c46106ce1fe2fa9dbdb559ef25860a95bdcfa5f82d58ae777157970078e49f8f058a03342d1ef1d561f68dd01b84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
